name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3.0.1
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v17
    - run: nix-build -A checks.$(nix-instantiate --eval -E '(builtins.currentSystem)')
